trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
# Step 1: Checkout repo
- checkout: self

# Step 2: Install Python 3 and dependencies
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install pandas sqlalchemy pyodbc
  displayName: 'Install Python Packages'

# Step 3: Run Python script to load CSVs into SQL
- script: |
    python load_csv.py
  displayName: 'Load CSVs into Azure SQL Database'
